bounswe/bounswe2020group9

.gitignore
practice-app/cmpe352API/app.py
practice-app/cmpe352API/bazaar_api.py
practice-app/cmpe352API/templates/menu.html
practice-app/cmpe352API/utils.py

pull additions to the parent branch

Api development favorites

---

practice-app/cmpe352API/api_calls.py
practice-app/cmpe352API/app.py
practice-app/cmpe352API/test_news.py
practice-app/cmpe352API/utils.py

Test cases are added for news and nasa news in "test_news.py".  Also small changes are made in other classes and some functions are added

News unit test

---

practice-app/cmpe352API/templates/index.html

Hope there wont be any merge problems

integrated /pi/apod into index.html

---

practice-app/cmpe352API/api_calls.py
practice-app/cmpe352API/templates/index.html

Frontend development astronomy picture of the day

---

practice-app/cmpe352API/test_weather.py

Forward date tests for Weather API are added for both get_weather and get_weather_today functions.

Weather API test cases additions

---

practice-app/cmpe352API/api_calls.py
practice-app/cmpe352API/templates/index.html
practice-app/cmpe352API/templates/main.css
practice-app/cmpe352API/test_news.py

Front end for news is completed. However it would be good if you check error handling

Front end development nasa news

---

.gitignore
Projects/Backend/src/api/settings.py
Projects/Backend/src/product/admin.py
Projects/Backend/src/product/apps.py
Projects/Backend/src/product/models.py
Projects/Backend/src/product/tests.py
Projects/Backend/src/product/views.py
Projects/Backend/src/user/models.py

> I think User-Product tables are initialized and working

Initialized User-Product tables

---

.gitignore
Projects/Backend/src/api/settings.py
Projects/Backend/src/location/admin.py
Projects/Backend/src/location/apps.py
Projects/Backend/src/location/models.py
Projects/Backend/src/location/tests.py
Projects/Backend/src/location/views.py
Projects/Backend/src/message/admin.py
Projects/Backend/src/message/apps.py
Projects/Backend/src/message/models.py
Projects/Backend/src/message/tests.py
Projects/Backend/src/message/views.py
Projects/Backend/src/product/models.py

Writing the initial tables, we can fill them later

added message, order, comment, location

---

Projects/Frontend/bazaar-frontend/package.json
Projects/Frontend/bazaar-frontend/src/components/Login/index.js
Projects/Frontend/bazaar-frontend/src/components/Signup/index.js
Projects/Frontend/bazaar-frontend/src/index.css
Projects/Frontend/bazaar-frontend/src/screens/Sign-In/index.js
Projects/Frontend/bazaar-frontend/src/screens/Sign-Up/index.js
Projects/Frontend/bazaar-frontend/yarn.lock

Basic login and signup features are done

login and signup components created.

---

Projects/Frontend/bazaar-frontend/src/components/Footer/index.css
Projects/Frontend/bazaar-frontend/src/components/Footer/index.js

A basic footer with year, site name and address information

Basic Footer

---

Projects/Backend/src/product/models.py

I thought that the relation between Product and Comment is one-to-many instead of one-to-one.

Comment Model editted

---

Projects/Backend/src/product/funcs.py
Projects/Backend/src/product/models.py
Projects/Backend/src/product/serializers.py

Backend omer product

---

Projects/Backend/src/product/functions.py
Projects/Backend/src/product/tests.py
Projects/Backend/src/product/views.py
Projects/Backend/src/user/functions.py

initial testCase

---

Projects/Backend/src/user/urls.py
Projects/Backend/src/user/views.py

Login needs to be updated after token implementation.

Login (wihtout tokens) implemented.

---

Projects/Frontend/bazaar-frontend/src/App.js
Projects/Frontend/bazaar-frontend/src/components/Login/index.js
Projects/Frontend/bazaar-frontend/src/components/Login/login.css
Projects/Frontend/bazaar-frontend/src/components/Profile-Page/index.js
Projects/Frontend/bazaar-frontend/src/components/Profile-Page/profilepage.css
Projects/Frontend/bazaar-frontend/src/components/Signup/index.js
Projects/Frontend/bazaar-frontend/src/components/Signup/signup.css
Projects/Frontend/bazaar-frontend/src/index.css
Projects/Frontend/bazaar-frontend/src/screens/Profile-page/index.js

profile page implemented, minor changes to signin and signup pages. removed signin/signup styles from index.css, added them to css files in component folders.

profile page implemented, minor changes to signin and signup pages

---

Projects/Backend/src/product/views.py
Projects/Backend/src/user/serializers.py
Projects/Backend/src/user/views.py

error handling, singup now requires email verification

Backend master omer api

---

Projects/Backend/src/location/urls.py
Projects/Backend/src/location/views.py

Token authorization is added. Multiple locations can be posted by 1 user. User can only view update or delete her/his locations.

Location API is finished.

---

Projects/Backend/src/location/models.py

Adding 2 fields(longitude-latitude) for location is enough.

2 new fields are added to support google maps

---

Projects/Frontend/bazaar-frontend/src/components/Footer/index.js

It seems good to me, what do you think?

Frontend ahmet footer update

---

Projects/Frontend/bazaar-frontend/src/App.js
Projects/Frontend/bazaar-frontend/src/components/Card/index.js
Projects/Frontend/bazaar-frontend/src/screens/Profile-page/index.js
Projects/Frontend/bazaar-frontend/src/screens/Profile-page/profilepage.css
Projects/Frontend/bazaar-frontend/src/screens/Sign-In/forgot-password.js
Projects/Frontend/bazaar-frontend/src/screens/Sign-Up/index.js
Projects/Frontend/bazaar-frontend/src/screens/Sign-Up/sign-up.css

signup and profile pages updated. form validation implemented.
forgot password page implemented.

Frontend firat

---

Projects/Backend/src/product/models.py
Projects/Backend/src/product/serializers.py
Projects/Backend/src/product/urls.py
Projects/Backend/src/product/views.py
Projects/Backend/src/user/urls.py

cart system working as intended

Backend omer cart

---

Projects/Backend/src/product/urls.py
Projects/Backend/src/user/views.py

added the API call `/api/product/vendor/<id>/`, requested by frontend

alternative API call: /api/product/vendor/<id>/

---

Projects/Mobile/Bazaar-iOS/Bazaar-iOS.xcodeproj/project.pbxproj
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Base.lproj/Main.storyboard
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/AddListViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/ListDetailViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/MainViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/WishlistViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Helper/Constants.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/APIManager.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/Parse Data/APIDatas.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/Requests/ApiRouter.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/ProductDetailViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/View/List Cell/ListCell.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/View/List Cell/ListCell.xib

Please review this pull request. Every comment would be appreciated, thanks :)

Ios beste wishlist

---

Projects/Backend/src/product/views.py

category option for POST Product

category option for POST Product

---

Projects/Backend/src/product/functions.py
Projects/Backend/src/product/models.py
Projects/Backend/src/product/serializers.py
Projects/Backend/src/product/urls.py
Projects/Backend/src/product/views.py
Projects/Backend/src/user/functions.py
Projects/Backend/src/user/tests.py
Projects/Backend/src/user/views.py

search functionality and user unit tests are added

Backend ibrahim search

---

Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Base.lproj/Main.storyboard
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/LoginViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/ProfileViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/SignUpViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Helper/Constants.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/MyAccountViewController.swift

- My account page design has been completed
- Name and surname are added instead of user email on my profile page. If there is no name and surname, the e-mail will be shown.
-   If users who log in with google want to reset their passwords, the warning screen will appear and they will not be able to reset their passwords.
- Added shadows to ui elements

Design of My Account Page

---

Projects/Backend/src/user/models.py
Projects/Backend/src/user/serializers.py
Projects/Backend/src/user/urls.py
Projects/Backend/src/user/views.py

Google signup and sign in added, signup for vendor is changed. Company is added to model

Backend ibrahim signupfix

---

Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Base.lproj/Main.storyboard
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/ListDetailViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/WishlistViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/APIManager.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/Parse Data/APIDatas.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/Requests/ApiRouter.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/ProductDetailViewController.swift

I think once approved this merge will finalize the Product Lists implementation (hopefully 🙏 ). 
- "Add to list" functionality is done.
- An alert is displayed when the user wants to delete a list with products in it.
- Also, a small change to the product detail page for choosing the amount of a product to add to cart. Now the default amount is 1.
Please review!

iOS - Lists (final version)

---

Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/LoginViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/SignUpViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/APIManager.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/Parse Data/APIDatas.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/Requests/ApiRouter.swift

Users who log in with Google will see a warning message when they try to change their password.
The required user information has been transferred successfully to the backend

iOS - Google sign in

---

Projects/Frontend/bazaar-frontend/src/screens/Profile-page/profile-page.js
Projects/Frontend/bazaar-frontend/src/screens/Sign-In/sign-in.js

Frontend firat errors

---

Projects/Frontend/bazaar-frontend/src/screens/Cart/Cart.js
Projects/Frontend/bazaar-frontend/src/screens/Cart/cart.scss
Projects/Frontend/bazaar-frontend/src/screens/MyList/MyList.js
Projects/Frontend/bazaar-frontend/src/screens/MyList/mylist.scss

Product list page added and made dynamic

Frontend hasan product lists

---

Projects/Frontend/bazaar-frontend/package.json
Projects/Frontend/bazaar-frontend/src/screens/Sign-In/index.js
Projects/Frontend/bazaar-frontend/yarn.lock

Sign in with google 
https://developers.google.com/identity/sign-in/web/reference

Frontend mcan google auth

---

Projects/Backend/src/api/settings.py
Projects/Backend/src/api/urls.py
Projects/Backend/src/location/views.py
Projects/Backend/src/product/functions.py
Projects/Backend/src/product/models.py
Projects/Backend/src/product/serializers.py
Projects/Backend/src/product/urls.py
Projects/Backend/src/product/views.py
Projects/Backend/src/user/functions.py
Projects/Backend/src/user/models.py
Projects/Backend/src/user/serializers.py
Projects/Backend/src/user/tests.py
Projects/Backend/src/user/urls.py
Projects/Backend/src/user/views.py

If there were any old branches, this commit changes nothing, you can revert it.
However, it is good to reformat the code once in a while

reformatted, removed old TODO's from backend_master

---

.gitignore
Projects/Frontend/bazaar-frontend/src/screens/Home/home.js
Projects/Frontend/bazaar-frontend/src/screens/Sign-Up/sign-up-vendor.js
Projects/Frontend/bazaar-frontend/src/screens/Sign-Up/sign-up.js

terms and conditions part added to signup page

Frontend master omer terms and conditions

---

Projects/Backend/src/api/settings.py
Projects/Backend/src/product/models.py
Projects/Backend/src/product/serializers.py
Projects/Backend/src/product/urls.py
Projects/Backend/src/product/views.py
Projects/Backend/src/user/views.py

Mail settings are changed and payment functions are added

New mail informations are added and payment functionality is added

---

Projects/Backend/src/message/models.py
Projects/Backend/src/message/urls.py
Projects/Backend/src/message/views.py

id overwriting bug is handled
GET all messages API is implemented
new GET conversations returns conversations ordered by timestamp

Backend kemaloglu message bug and new API

---

Projects/Backend/src/message/views.py

Return 500 handled with try-except

Messaging system - Small bug

---

Projects/Frontend/bazaar-frontend/src/App.js
Projects/Frontend/bazaar-frontend/src/components/Header/Header.js
Projects/Frontend/bazaar-frontend/src/components/category-bar/category-bar.js
Projects/Frontend/bazaar-frontend/src/screens/Messages/messages.js
Projects/Frontend/bazaar-frontend/src/screens/Messages/messages.scss

Message page done, works quite well but ugly

Frontend omer message

---

Projects/Frontend/bazaar-frontend/src/components/Header/Header.js
Projects/Frontend/bazaar-frontend/src/screens/Messages/messages.js
Projects/Frontend/bazaar-frontend/src/screens/Messages/messages.scss

Notification looks complete, but it will need css makeup

Frontend omer notification

---

Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Base.lproj/Main.storyboard
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/MainViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/VendorProfileForUserViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/Parse Data/APIDatas.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/ProductDetailViewController.swift

vendor profile for customer side is completed with following properties:
- name of the company, average reviews, products of the vendor is shown. address information can be shown but is hidden for now.
- a button is added for messaging with the vendor, however it is not fully functional for now. i'm waiting for messaging view to be completed to implement that part.

iOS - alcan - vendor profile for customer developments

---

Projects/Backend/src/product/models.py
Projects/Backend/src/product/tests.py
Projects/Backend/src/product/views.py
Projects/Backend/src/user/tests.py

unit tests are added and order response is changed

Backend ibrahim test

---

Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Base.lproj/Main.storyboard
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/VendorMyAccountViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/APIManager.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/Requests/ApiRouter.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/MyAccountViewController.swift

Delete account functionality is completed with following properties:
- Customers and vendors will be able to delete their account completely.

iOS - Delete Account

---

Projects/Backend/src/product/urls.py
Projects/Backend/src/product/views.py

API doesn't return anonymous comments.
API doesn't need token anymore

#325 API is updated.

---

Projects/Mobile/Bazaar-iOS/Bazaar-iOS.xcodeproj/project.pbxproj
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Base.lproj/Main.storyboard
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/VendorAddNewAddressViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/VendorMyAddressesViewController.swift

Vendor My Addresses page is completed with following properties:
Vendors will be able to
- save their address
- remove their address
- view their address
- update their address

iOS -  Vendor My Addresses

---

Projects/Frontend/bazaar-frontend/package.json
Projects/Frontend/bazaar-frontend/src/App.js
Projects/Frontend/bazaar-frontend/src/components/category-bar/category-bar.js
Projects/Frontend/bazaar-frontend/src/screens/Cart/Checkout/AddressCard/addresscard.js
Projects/Frontend/bazaar-frontend/src/screens/Cart/Checkout/AddressCard/addresscard.scss
Projects/Frontend/bazaar-frontend/src/screens/Cart/Checkout/CreditCardCard/creditcardcard.js
Projects/Frontend/bazaar-frontend/src/screens/Cart/Checkout/CreditCardCard/creditcardcard.scss
Projects/Frontend/bazaar-frontend/src/screens/Cart/Checkout/CreditCardView.js
Projects/Frontend/bazaar-frontend/src/screens/Cart/Checkout/checkout.js
Projects/Frontend/bazaar-frontend/src/screens/Cart/Checkout/checkout.scss
Projects/Frontend/bazaar-frontend/src/screens/Profile-page/profile-page.js
Projects/Frontend/bazaar-frontend/src/screens/Profile-page/profilepage.scss
Projects/Frontend/bazaar-frontend/src/screens/SearchResults/search-results.js
Projects/Frontend/bazaar-frontend/src/screens/Sign-Up/sign-up-vendor.js
Projects/Frontend/bazaar-frontend/yarn.lock

Order page is done.  Some style changes might be needed.

Frontend firat order

---

Projects/Mobile/Bazaar-iOS/Bazaar-iOS.xcodeproj/project.pbxproj
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Base.lproj/Main.storyboard
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/LegalPolicyViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/SignUpViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/APIManager.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/Requests/ApiRouter.swift

'Sign Up and Legal Policies' task is completed with following properties:
- Legal agreements that we want users to accept while signing up have been added.
- New improvements have been made according to the sign up updates on the backend side.

iOS -  Sign Up and Legal Policies

---

Projects/Frontend/bazaar-frontend/src/screens/Messages/messages.js
Projects/Frontend/bazaar-frontend/src/screens/Messages/messages.scss
Projects/Frontend/bazaar-frontend/src/screens/ProductPage/CommentCard/CommentCard.js
Projects/Frontend/bazaar-frontend/src/screens/ProductPage/CommentCard/commentCard.scss
Projects/Frontend/bazaar-frontend/src/screens/ProductPage/ProductPage.js
Projects/Frontend/bazaar-frontend/src/screens/ProductPage/productpage.scss

Comment structure fully working. Please review

Frontend hasan comments

---

Projects/Frontend/bazaar-frontend/src/App.js
Projects/Frontend/bazaar-frontend/src/components/Header/Header.js
Projects/Frontend/bazaar-frontend/src/screens/MyAdresses/MyAddresses.js
Projects/Frontend/bazaar-frontend/src/screens/MyAdresses/MyAddresses.scss

My addresses page logically is done.

MyAddresses page created

---

Projects/Mobile/Bazaar-iOS/Bazaar-iOS.xcodeproj/project.pbxproj
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Base.lproj/Main.storyboard
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/NotificationsViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/APIManager.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/Parse Data/APIDatas.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/Requests/ApiRouter.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/View/Notification Cell/NotificationCell.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/View/Notification Cell/NotificationCell.xib

Customer Notifications Page initial setup is completed with following property fields:
* Notification message 
* Seen Status
* Product Name 
* Time Label
* Product Image

Customer Notifications Page initial setup

---

Projects/Mobile/Bazaar-iOS/Bazaar-iOS.xcodeproj/project.pbxproj
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Base.lproj/Main.storyboard
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/NotificationsViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/VendorNotificationViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/View/Notification Cell/NotificationCell.xib

Vendor Notifications Page setup is completed with following property fields:
* Notification message 
* Seen Status
* Product Name 
* Time Label
* Product Image
* Waiting for backend team to update notification fields.

Vendor Notifications Page

---

Projects/Frontend/bazaar-frontend/src/App.js
Projects/Frontend/bazaar-frontend/src/components/Header/Header.js
Projects/Frontend/bazaar-frontend/src/screens/Cart/Checkout/checkout.js
Projects/Frontend/bazaar-frontend/src/screens/Inventory/inventory.js
Projects/Frontend/bazaar-frontend/src/screens/Inventory/inventory.scss
Projects/Frontend/bazaar-frontend/src/screens/MyOrders/my-orders-vendor.js
Projects/Frontend/bazaar-frontend/src/screens/MyOrders/my-orders-vendor.scss
Projects/Frontend/bazaar-frontend/src/screens/MyOrders/my-orders.js
Projects/Frontend/bazaar-frontend/src/screens/MyOrders/my-orders.scss

my orders pages for customer and vendor complete.

Frontend firat myorders page

---

Projects/Backend/src/message/models.py
Projects/Backend/src/product/functions.py
Projects/Backend/src/product/views.py

I added new field (delivery_id) to notifications. I hope there wiil be no migration problems during deployment @ocebenzer.
I did small changes in order and delivery codes. It would be nice if you check the changes before the merge @ibrahimorhan.

Delivery_id field is added to notification model.

---

Projects/Backend/src/product/views.py

Co-Authored-By: Mehmet Berk Kemaloğlu <berk.kemaloglu@boun.edu.tr>
context is added to product serializers

context is added to product serializers

---

Projects/Frontend/bazaar-frontend/src/components/Footer/Footer.js
Projects/Frontend/bazaar-frontend/src/components/Footer/footer.css

Category names and links were updated.

Footer update

---

Projects/Mobile/Bazaar-iOS/Bazaar-iOS.xcodeproj/project.pbxproj
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Base.lproj/Main.storyboard
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/CustomerOrdersViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/NotificationsViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/OrderDetailViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/PaymentViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/APIManager.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/Requests/ApiRouter.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/View/Order Cell/OrderCell.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/View/Order Cell/OrderCell.xib
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/View/Product Cell/ProductCell.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/View/Product Cell/ProductCell.xib

Order Detail Page is completed with following properties:
* Name & Brand 
* Price & Order Status
* Amount
* Given Date & Estimated Delivery Date
* Order Address
* Canceling order mechanism is working right now.

Order Detail Page 

---

Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Base.lproj/Main.storyboard
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/CustomerOrdersViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/NotificationsViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/OrderDetailViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/VendorMyOrdersViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/VendorNotificationViewController.swift

Vendor My Orders Page is integrated with Order Details Page, includes following properties:
* Name & Brand 
* Price & Order Status
* Amount
* Given Date & Estimated Delivery Date
* Order Address
* Swipe action function updated. Changing order status by swipe enabled. Swipe action titles are corrected.
* Swipe action disabled for orders with status "Canceled", "On the way"
* Minor font updates have been applied to notifications.

IOS-Vendor Order Details

---

Projects/Frontend/bazaar-frontend/src/App.js
Projects/Frontend/bazaar-frontend/src/components/Header/Header.js
Projects/Frontend/bazaar-frontend/src/components/ProductCard/productCard.js
Projects/Frontend/bazaar-frontend/src/components/category-bar/category-bar.js
Projects/Frontend/bazaar-frontend/src/screens/Add-Product/addproduct.js
Projects/Frontend/bazaar-frontend/src/screens/Cart/Cart.js
Projects/Frontend/bazaar-frontend/src/screens/Cart/Checkout/AddressCard/addresscard.js
Projects/Frontend/bazaar-frontend/src/screens/Cart/Checkout/CreditCardCard/creditcardcard.js
Projects/Frontend/bazaar-frontend/src/screens/Cart/Checkout/checkout.js
Projects/Frontend/bazaar-frontend/src/screens/Home/home.js
Projects/Frontend/bazaar-frontend/src/screens/Inventory/inventory.js
Projects/Frontend/bazaar-frontend/src/screens/Messages/messages.js
Projects/Frontend/bazaar-frontend/src/screens/MyAdresses/MyAddresses.js
Projects/Frontend/bazaar-frontend/src/screens/MyComments/MyCommentCard/MyCommentCard.js
Projects/Frontend/bazaar-frontend/src/screens/MyComments/MyCommentProduct/MyCommentProduct.js
Projects/Frontend/bazaar-frontend/src/screens/MyComments/MyComments.js
Projects/Frontend/bazaar-frontend/src/screens/MyList/MyList.js
Projects/Frontend/bazaar-frontend/src/screens/MyOrders/my-orders-vendor.js
Projects/Frontend/bazaar-frontend/src/screens/MyOrders/my-orders.js
Projects/Frontend/bazaar-frontend/src/screens/ProductPage/ProductPage.js
Projects/Frontend/bazaar-frontend/src/screens/Profile-page/profile-page.js
Projects/Frontend/bazaar-frontend/src/screens/Profile-page/user-page.js
Projects/Frontend/bazaar-frontend/src/screens/SearchResults/search-results.js
Projects/Frontend/bazaar-frontend/src/screens/ShowList/ShowList.js
Projects/Frontend/bazaar-frontend/src/screens/Sign-In/forgot-password.js
Projects/Frontend/bazaar-frontend/src/screens/Sign-In/reset-pw.js
Projects/Frontend/bazaar-frontend/src/screens/Sign-In/sign-in.js
Projects/Frontend/bazaar-frontend/src/screens/Sign-Up/activate.js
Projects/Frontend/bazaar-frontend/src/screens/Sign-Up/sign-up.js
Projects/Frontend/bazaar-frontend/src/screens/ViewCategory/view-category.js

Removed many of the compiler warnings but there are still some left.

frontend cleanup

---

Projects/Mobile/Bazaar-iOS/Bazaar-iOS.xcodeproj/project.pbxproj
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Base.lproj/Main.storyboard
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/AddReviewViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/MyReviewsViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Controller/OrderDetailViewController.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/APIManager.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/Model/Requests/ApiRouter.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/View/Order Cell/OrderCell.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/View/Review Cell/ReviewTableViewCell.swift
Projects/Mobile/Bazaar-iOS/Bazaar-iOS/View/Review Cell/ReviewTableViewCell.xib

Reviews functionalities have been added:
- My Reviews page: + editing/deleting reviews
- Adding reviews to ordered product (from My Orders page), if review already exists it can be edited
--- 
Please comment on this final pull request of mine :)

iOS - reviews
